<a href="https://colab.research.google.com/github/ltpereyra/API-Django/blob/master/BootCamp_Udemy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Exercise 1




**Inspecting a Array NumPy**

A numpy object has attributes and methods inherited from the class (numpy.ndarray). Creat an array and inspect the following attributes:

Shape: A tuple containing a number of elements (size) in each dimension of the array;

Size: Total number of elements in the array;

ndim: Number of dimensions (axes);

nbytes: Number of bytes used to store the data;

dtype: The data type of the elements in the array;


In [ ]:
import numpy as np

array = np.array([[1,2,3,4],[5,6,7,8]])
print("Shape: ", array.shape)
print("Size: ", array.size)
print("ndim: ", array.ndim)
print("nbytes: ", array.nbytes)
print("dtype: ", array.dtype)

Shape:  (2, 4)
Size:  8
ndim:  2
nbytes:  64
dtype:  int64


# Exercise 2


Based on the previous exercise, create a function that can receive an array and shows on the screen its attributes. Check if the insert argument is, indeed, a numpy object. You can also use a built-in type () function to verify the object' class.

Expected return:
```
inspect_array(np.array([1,2,3])) 
 
Shape : (3,)
Size:  3
Ndim:  1
Nbytes:  24
Dtype:  int64
Type:  <class 'numpy.ndarray'>
array([1, 2, 3])


inspect_array([1,2,3]) 
'The inserted object is not a NumPy array.'
```




In [ ]:
import numpy as np

def inspect_array(array):
  if isinstance(array,np.ndarray):
    print("Shape: ", array.shape)
    print("Size: ", array.size)
    print("ndim: ", array.ndim)
    print("nbytes: ", array.nbytes)
    print("dtype: ", array.dtype)
    print(array)
  else:
    print("The inserted object is not a NumPy array.")

array = np.array([[1,2,3,4],[5,6,7,8]])
inspect_array(array)

notarray = [1,2,3,4]
inspect_array(notarray)

Shape:  (2, 4)
Size:  8
ndim:  2
nbytes:  64
dtype:  int64
[[1 2 3 4]
 [5 6 7 8]]
The inserted object is not a NumPy array.


# Exercise 3



Use the np.array() function to creat the one-dimensioned arrays listed below:

a) Use a list as an argument and obtain:

`array([-1,  4,  7,  9])`


b) Use the range() function and obtain:

`array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])`


c) Use a tuple as an argument and obtain:

`array([10, 11, 12, 13, 14])`


d) Use the range() function and obtain:

`array([1990, 1995, 2000, 2005, 2010, 2015, 2020])`


e) Use the range() function and obtain:

`array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920, 1910, 1900])`


f) Obtain:

`array(100)`

In [ ]:
import numpy as np

# a)
array1 = np.array([-1,4,7,9])

# b)
array2 = np.array(range(1,11))

# c)
tuple_ = (10,11,12,13,14)
array3 = np.array(tuple_)

# d)
array4 = np.array(range(1990,2021,5))

# e)
array5 = np.array(range(2020,1890,-10))

# f)
array6 = np.array(100)

print(array1)
print(array2)
print(array3)
print(array4)
print(array5)
print(array6)





[-1  4  7  9]
[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14]
[1990 1995 2000 2005 2010 2015 2020]
[2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]
100


# Exercise 4



The np.ones() function allows you to create an array filled with the number 1 in all your entries. We can specify as arguments the shape and the kind of dtype of the array. Use this function to create the following arrays:

a)
```
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```

b)
```
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```

c)

```
array([[1., 1.],
       [1., 1.],
       [1., 1.]])
```


In [ ]:
import numpy as np

array1 = np.ones(10)
print(array1,"\n")

array2 = np.ones((4,4))
print(array2,"\n")

array3 = np.ones((3,2))
print(array3,"\n")

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 



# Exercise 5


The np.zeros() function allows you to create an array filled with the number 0 in all your entries. We can specify as arguments the shape and the kind of dtype of the array (default is the float). Use this function to create the following arrays:

a)
```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

b)
```
array([[0., 0.],       
      [0., 0.]])
```

c)
```
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])
```

In [76]:
import numpy as np

# a)
array1 = np.zeros(10)
print(array1,"\n")

# b)
array2 = np.zeros((2,2))
print(array2,"\n")

# c)
array3 = np.zeros((4,6))
print(array3,"\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0.]
 [0. 0.]] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 



# Exercise 6


Create the following arrays:

a)
```
array([[10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45]])
```

b)
```
array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])
```

c)
```
array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])
```

Tip: use np.arange() or np.array(range()).

In [ ]:
import numpy as np

# a)
array1 = np.arange(10,46,5).reshape(8,1) ## podria ser .reshape(-1,1)
print(array1,"\n")

# b)
array2 = np.arange(-50,-4,5)
print(array2,"\n")

# c)
array3 = np.arange(50,150,2).reshape(5,10)
print(array3,"\n")

[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]] 

[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5] 

[[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]] 



# Exercise 7


Use the np.full(shape, fill_value, dtype) function to create the following arrays. This function allows you to create an array with a user-defined shape and dtype, filled with a certain value.

a)
```
array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])
```



b)
```
array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])
```

c)
```
array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])
```

d)
```
array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])
```

Tip: Another possibility would be to obtain the arrays with a different operation, by mutiplying a matrix filled with the number 1 by a certain value.

In [ ]:
import numpy as np

# a)
array1 = np.full((1,10),5,float)
print(array1,"\n")

# b)
array2 = np.full((4,4),-5,float)
print(array2,"\n")

# c)
array3 = np.full((3,3),3)
print(array3,"\n")

# d)
array4 = np.full((10,10),50)
print(array4,"\n")

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]] 

[[-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]] 

[[3 3 3]
 [3 3 3]
 [3 3 3]] 

[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]] 



# Exercise 8




Define the K array and check for missing data. Use the np.isnan() function.

```
array([[ nan,   1.,  10.,   0.],
       [ nan,  nan,  nan,  nan],
       [100.,  50.,  nan, -25.],
       [ 30.,  nan,  nan, 130.]])
```


In [ ]:
import numpy as np

K = np.array(([np.nan, 1, 10, 0],
             [np.nan, np.nan, np.nan, np.nan],
             [100, 50,  np.nan, -25],
             [30, np.nan, np.nan, 130]))

print(np.isnan(K),"\n")
print(f"Hay {np.isnan(K).sum()} NaN en array")

[[ True False False False]
 [ True  True  True  True]
 [False False  True False]
 [False  True  True False]] 

Hay 8 NaN en array


#Exercise 9


The np.linspace () function returns an array of evenly spaced numbers within a defined range. Create an array with numbers within the range [1,21] in 5 parts.

Expected return:

`array([ 1.,  6., 11., 16., 21.])`

In [ ]:
import numpy as np

array = np.linspace(1,21,5)
print(array)

[ 1.  6. 11. 16. 21.]


#Exercise 10


The np.logspace () function returns evenly spaced numbers on a logarithmic scale. Create an array with numbers within the range [1,51] in 10 parts with the np.logspace() function.

Expected return:

```
array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])
```




In [ ]:
import numpy as np

array = np.logspace(1,51,10).reshape(-1,1)
print(array)

[[1.00000000e+01]
 [3.59381366e+06]
 [1.29154967e+12]
 [4.64158883e+17]
 [1.66810054e+23]
 [5.99484250e+28]
 [2.15443469e+34]
 [7.74263683e+39]
 [2.78255940e+45]
 [1.00000000e+51]]


#Exercise 11


Use the np.diag() function to build the following array:

```
array([[ 5,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  0, 25,  0],
       [ 0,  0,  0,  0,  0, 30]])
```




In [ ]:
import numpy as np

array = np.arange(5,31,5)
arraydiag = np.diag(array)
print(arraydiag)

[[ 5  0  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 20  0  0]
 [ 0  0  0  0 25  0]
 [ 0  0  0  0  0 30]]


#Exercise 12


Use the np.eye() function (or even np.identity()) to obtain the following array.

```
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])
```

Tip: this matrix is ​​defined as an identity matrix, in this case of order 10, and it assumes great relevance in several computational calculations, as we will see later.

In [ ]:
import numpy as np

array = np.eye(10,10,1,float)
print(array,"\n")

array = np.identity(10)
print(array)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#Exercise 14


Obtain the sum of the elements of each array below. Use the np.sum () function. Implement a solution with "loop for", to do so, store the vectors in a list.

```
import numpy as np

array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))
```

Expected return:

```
Sum of the elements of array 1:  55
Sum of the elements of array 2:  255.0
Sum of the elements of array 3:  1275
Sum of the elements of array 4:  10056552148.564463
Sum of the elements of array 5:  105
```

In [ ]:
import numpy as np
 
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))
arraylist = [array1, array2, array3, array4, array5]

for index, array in enumerate(arraylist,1):
  print(f"La suma de array{index} es: {array.sum()}")

La suma de array1 es: 55
La suma de array2 es: 255.0
La suma de array3 es: 1275
La suma de array4 es: 10056552148.564463
La suma de array5 es: 105


#Exercise 15


From the matrix defined below, obtain:

a) total sum of the elements;

b) sum of the lines;

c) sum of columns.

```
import numpy as np
matrix = np.array(np.random.randint(1,100,15)).reshape(5,3)
```

In [ ]:
import numpy as np

matrix = np.array(np.random.randint(1,100,15)).reshape(5,3)
print(matrix,"\n")

# a)
print(matrix.sum(),"\n")

# b)
print(matrix.sum(1),"\n")

# c)
print(matrix.sum(0))

[[ 2 17 46]
 [58 64 29]
 [ 3 54 36]
 [51 42 75]
 [74 36  7]] 

594 

[ 65 151  93 168 117] 

[188 213 193]


#Exercise 16


Obtain the maximum and minimum value of each array below. Implement a solution with a "loop for".

```
import numpy as np

array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))
```

Tip: To obtain the maximum and minimium value of an array, we can use array.max() and array.min() (or max(array) and min(array)).

In [ ]:
import numpy as np

array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))
arraylist = [array1, array2, array3, array4]

for index,array in enumerate(arraylist,1):
    print(f"Array{index}:\n Máx.: {array.max()}\n Mín.: {array.min()}\n")

Array1:
 Máx.: 27
 Mín.: -1

Array2:
 Máx.: 293
 Mín.: -76

Array3:
 Máx.: 1.9437912570653972
 Mín.: -0.9659667741316402

Array4:
 Máx.: 50
 Mín.: 12



#Exercise 17


Create a function that receives a matrix as input and calculate:

a) Maximum value of the matrix;
b) Maximum value per column;
c) Maximum value per line;
d) Minimum value of the matrix;
e) Minimum value per column;
f) Minimum value per line.

Example of return for the matrix defined below:

Input:

```
matrix = np.random.randint(-1000,1000,50).reshape(10,5)
info_array(array)
```
Output:
```
Maximum value of the matrix:  987
Maximum value per column:  [959 987 597 748 719]
Maximum value per line:  [ 987  312  982  204  719  689  101  793 -460  959]
Minimum value of the matrix:  -969
Minimum value per column:  [-878 -966 -969 -884 -881]
Minimum value per line:  [  30 -878 -335 -863  -40 -289 -660 -239 -969 -966]
```

In [11]:
import numpy as np
 
def info_array(matrix):
    print("Maximum value of the matrix: ",matrix.max())
    print("Maximum value per column: ",matrix.max(0))
    print("Maximum value per line: ",matrix.max(1))
    print("Minimum value of the matrix: ",matrix.min())
    print("Minimum value per column: ",matrix.min(0))
    print("Minimum value per line: ",matrix.min(1))

matrix = np.random.randint(-1000,1000,50).reshape(10,5)
info_array(matrix)

Maximum value of the matrix:  921
Maximum value per column:  [316 833 921 916 589]
Maximum value per line:  [547 110 441 921 453 849 589 414 381 441]
Minimum value of the matrix:  -981
Minimum value per column:  [-942 -935 -856 -981 -884]
Minimum value per line:  [-942 -693 -803 -884 -667 -981 -935 -856 -222 -669]


#Exercise 18


Based on the array defined below, obtain your average, median, variance, and standard deviation.

```
import numpy as np

arr = np.random.normal(40,0.5,size = (300))
```

Tip:

Average: np.mean();

Median: np.median();

Standard deviation: np.std();

Variance: np.var().

In [14]:
import numpy as np
 
arr = np.random.normal(40,0.5,size = (300))

print("Average: ",np.mean(arr))
print("Median: ",np.median(arr))
print("Standard deviation: ", np.std(arr))
print("Variance: ",np.var(arr))

Average:  39.983122186737894
Median:  39.94799094401697
Standard deviation:  0.5015973390300665
Variance:  0.2515998905220435


#Exercise 19


Based on the arrays defined below, obtain the covariance matrix and the correlation matrix.

```
import numpy as np

x = np.random.rand(100)
y = np.random.uniform(size=100)
```

Tip: use np.corrcoef() and np.cov().

In [17]:
import numpy as np
 
x = np.random.rand(100)
y = np.random.uniform(size=100)

print("Convariance matrix:\n", np.corrcoef(x,y))
print(f"Correlation matrix:\n {np.cov(x,y)}")

Convariance matrix:
 [[1.         0.05358501]
 [0.05358501 1.        ]]
Correlation matrix:
 [[0.0876403  0.00421621]
 [0.00421621 0.0706406 ]]


#Exercise 20


Get the index of the maximum value of array A.

```
A = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])
```

Tip: use np.argmax() or array.argmax().

In [21]:
import numpy as np

array = np.array([[11, 15, 33, 105],
                  [1, 140, 45, 90],
                  [67, 230, 78, 99]])

print(np.argmax(array))
print(array.argmax())
print(array.max())

9
9
230


#Exercise 21


Get the index of the minimum value of array B.

```
B = np.array([[73, 22, 20, 62,  3],
              [68, 84, 27, 59, 93],
              [48, 52,  4, 55, 50],
              [42, 23, 63, 67,  4],
              [44, 30, 41, 31, 29]])
```

Tip: use np.argmin() or array.argmin().

In [23]:
import numpy as np

array = np.array([[73, 22, 20, 62,  3],
                  [68, 84, 27, 59, 93],
                  [48, 52,  4, 55, 50],
                  [42, 23, 63, 67,  4],
                  [44, 30, 41, 31, 29]])

print(array.min())
print(np.argmin(array))
print(array.argmin())

3
4
4


#Exercise 22


Write a function that receives a NumPy array and shows a set of descriptive statistics for this object on the screen.

Expected result:

Input
```
array = np.array([-57, 101, 270, 130, 144])
info_array(array)
```

Output:
```
Max: 270
Min: -57
Mean: 117.6
Median: 130.0
Variance: 10967.439999999999
Standard deviation: 104.72554607162475
```

In [26]:
import numpy as np

def info_array(array):
    print(f"Max: {array.max()}")
    print(f"Min: {array.min()}")
    print(f"Mean: {np.mean(array)}")
    print(f"Median: {np.median(array)}")
    print(f"Variance: {array.var()}")
    print(f"Standard deviation: {array.std()}")

array = np.array([-57, 101, 270, 130, 144])
info_array(array)

Max: 270
Min: -57
Mean: 117.6
Median: 130.0
Variance: 10967.439999999999
Standard deviation: 104.72554607162475


#Exercise 23


Use the np.unique() function to obtain an array with the unique elements of the array below. To do so, store the new array in a variable.

```
A = np.array([[1, 3, 3, 4, 5],
              [4, 7, 11, 3, 5],
              [1, 11, 4, 4, 11]])
```





In [28]:
import numpy as np

array = np.array([[1, 3, 3, 4, 5],
                  [4, 7, 11, 3, 5],
                  [1, 11, 4, 4, 11]])

uni_array = np.unique(array)
print(uni_array)

[ 1  3  4  5  7 11]


#Exercise 24


Considering the arrays below:

```
import numpy as np

array1 = np.array([10, 20, 30, 40])
array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])
```

Obtain:

a) The first, the third, and the last element of each array;

b) Invert the array;

c) Take the number 20 in both of the arrays and store the sum in a variable.

In [62]:
import numpy as np

array1 = np.array([10, 20, 30, 40])
array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])
arraylist = [array1, array2]

# a)
print("a)")
for index, array in enumerate(arraylist,1):
    print(f"First element of array{index} is: {array[0]}")
    print(f"Third element of array{index} is: {array[2]}")
    print(f"Last element of array{index} is: {array[-1]}\n")

# b)
print("b)")
print(array1[::-1])
print(array2[::-1],"\n")

# c)
print("c)")
sum_ = 0
for index, array in enumerate(arraylist):
    for i in arraylist[index]:
        if i == 20:
            sum_ = sum_ + array[index]
print(sum_)

a)
First element of array1 is: 10
Third element of array1 is: 30
Last element of array1 is: 40

First element of array2 is: 100
Third element of array2 is: 5
Last element of array2 is: 170

b)
[40 30 20 10]
[170 155 130  20 100  40   1   5  30 100] 

c)
40


#Exercise 25


Access the numbers 9 and 90 of the array below.

```
import numpy as np

ar = np.array([[-1, 33, 44, 9, 1],[11, 1, 0, 90, 44]])
```




In [63]:
import numpy as np

ar = np.array([[-1, 33, 44, 9, 1],[11, 1, 0, 90, 44]])

print(ar[0][-2])
print(ar[1][-2])

9
90


#Exercise 26


3-D array indexing

Access the number 5, 9, 3 and 21 from the array below


```
import numpy as np

ar = np.array([[[1, 1, 5, 1],
                [1, 1, 1, 9]],
                [[1, 3, 1, 1],
                [1, 1, 21, 1]]])
```




In [72]:
import numpy as np

ar = np.array([[[1, 1, 5, 1],
                [1, 1, 1, 9]],
                [[1, 3, 1, 1],
                [1, 1, 21, 1]]])

print(ar[0][0][2])
print(ar[0][1][3])
print(ar[1][0][1])
print(ar[1][1][2])

5
9
3
21


#Exercise 27


1-D Slicing

Based on the array below, obtain the slice from index 2 to index 6.

```
import numpy as np

ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
```

Tip: In Python, slicing means that we can select elements between specified indexes. Syntax: [start:end:pass].

If we do not specify the start, the default value will be 0. If we do not define the step, the value 1 will be considered.

In [74]:
import numpy as np
 
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(ar[2:7])

[3 4 5 6 7]
